#!/usr/bin/env python3
"""Generate the stats index files from challenge metadata.

Scans ``platforms/**/metadata.json`` and (re)writes:

    stats/index-overview.md       - global totals across every platform
    stats/index-<platform>.md     - per-platform breakdown (one per active platform)

Counting model
--------------
A *challenge* is a distinct ``(platform, id)`` pair. The same challenge solved
in several languages has one folder per language but counts as a single
challenge everywhere EXCEPT the "solved per language" breakdown, where each
language solution is counted once (so per-language counts can sum to more than
the total number of challenges).

Per the repository owner's definition, the overview metric "total catalogued
patterns" is the number of *distinct topics* (``metadata.topics``) seen across
all platforms and languages, deduplicated. The per-platform "solved per type"
breakdown also uses ``topics``.

Determinism
-----------
Output is fully sorted and carries no wall-clock timestamp, so re-running it
without any metadata change produces no diff. This keeps the pre-commit hook
idempotent. Run it manually with ``python scripts/gen_indexes.py`` or let the
hook (``core.hooksPath = scripts/hooks``) run it on every commit.
"""

from __future__ import annotations

import json
import re
from collections import Counter
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
PLATFORMS = REPO / "platforms"
STATS = REPO / "stats"
README = REPO / "README.md"

GEN_NOTE = "> Auto-generated by `scripts/gen_indexes.py`. Do not edit by hand."
STATS_BEGIN = "<!--STATS:BEGIN-->"
STATS_END = "<!--STATS:END-->"
DIFF_ORDER = {"Easy": 0, "Medium": 1, "Hard": 2}


# --------------------------------------------------------------------------- #
# Sort keys
# --------------------------------------------------------------------------- #
def id_key(cid: str):
    """Numeric ids sort numerically; slug ids sort alphabetically after them."""
    return (0, int(cid)) if cid.isdigit() else (1, cid)


def diff_key(name: str):
    return (DIFF_ORDER.get(name, 99), name)


def count_key(item):
    """Sort (name, count) pairs by count desc, then name asc."""
    name, count = item
    return (-count, name)


# --------------------------------------------------------------------------- #
# Data loading
# --------------------------------------------------------------------------- #
def load_challenges() -> dict:
    """Aggregate every metadata.json into a {(platform, id): info} dict."""
    challenges: dict[tuple[str, str], dict] = {}
    for meta in PLATFORMS.glob("*/*/*/metadata.json"):
        try:
            data = json.loads(meta.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            raise SystemExit(f"Invalid JSON in {meta}: {exc}")

        platform = data.get("platform") or meta.parents[2].name
        cid = str(data.get("id") or meta.parent.name.split("-", 1)[0])
        key = (platform, cid)

        info = challenges.setdefault(
            key,
            {
                "platform": platform,
                "id": cid,
                "title": "",
                "difficulty": "Unknown",
                "topics": set(),
                "url": "",
                "langs": {},  # language -> platformPath (posix, repo-relative)
            },
        )
        if data.get("title"):
            info["title"] = data["title"]
        if data.get("difficulty"):
            info["difficulty"] = data["difficulty"]
        if data.get("url"):
            info["url"] = data["url"]
        for topic in data.get("topics", []):
            info["topics"].add(topic)

        lang = data.get("language") or data.get("languageExt") or "Unknown"
        ppath = data.get("platformPath") or meta.parent.relative_to(REPO).as_posix()
        info["langs"][lang] = ppath.replace("\\", "/")

    return challenges


def catalogued_platforms() -> int:
    """Number of platform directories catalogued under platforms/."""
    if not PLATFORMS.is_dir():
        return 0
    return sum(1 for p in PLATFORMS.iterdir() if p.is_dir())


# --------------------------------------------------------------------------- #
# Rendering helpers
# --------------------------------------------------------------------------- #
def render_count_table(header: str, counter: Counter, key=count_key) -> list[str]:
    lines = [f"| {header} | Solved |", "| --- | ---: |"]
    for name, count in sorted(counter.items(), key=key):
        lines.append(f"| {name} | {count} |")
    return lines


# --------------------------------------------------------------------------- #
# Overview
# --------------------------------------------------------------------------- #
def overview_metrics(challenges: dict) -> dict:
    """Headline overview numbers shared by the stats index and the README banner.

    A challenge is a distinct ``(platform, id)`` pair; per-language solutions of
    the same challenge each add one to the language counts.
    """
    by_platform: Counter = Counter(c["platform"] for c in challenges.values())
    languages: Counter = Counter()
    topics: set[str] = set()
    for c in challenges.values():
        for lang in c["langs"]:
            languages[lang] += 1
        topics |= c["topics"]
    return {
        "by_platform": by_platform,
        "languages": languages,
        "topics": topics,
        "total_challenges": len(challenges),
        "active_platforms": len(by_platform),
        "catalogued": catalogued_platforms(),
        "total_languages": len(languages),
        "total_patterns": len(topics),
    }


def build_overview(challenges: dict) -> str:
    m = overview_metrics(challenges)
    by_platform = m["by_platform"]
    languages = m["languages"]
    topics = m["topics"]
    total_challenges = m["total_challenges"]
    active_platforms = m["active_platforms"]
    catalogued = m["catalogued"]
    total_languages = m["total_languages"]
    total_patterns = m["total_patterns"]  # distinct topics, per owner's definition

    out: list[str] = [
        "# Index — Overview",
        "",
        GEN_NOTE,
        "",
        "| Metric | Value |",
        "| --- | ---: |",
        f"| Total challenges solved | {total_challenges} |",
        f"| Total source platforms | {active_platforms} (of {catalogued} catalogued) |",
        f"| Total languages used | {total_languages} |",
        f"| Total catalogued patterns | {total_patterns} |",
        "",
        "_\"Catalogued patterns\" counts distinct topics across all platforms and "
        "languages._",
        "",
        "## Platforms",
        "",
    ]
    if by_platform:
        out += ["| Platform | Challenges solved |", "| --- | ---: |"]
        for platform, count in sorted(by_platform.items(), key=count_key):
            out.append(f"| [{platform}](index-{platform}.md) | {count} |")
    else:
        out.append("_No challenges solved yet._")
    out += ["", "## Languages used", ""]
    if languages:
        out += render_count_table("Language", languages)
    else:
        out.append("_None yet._")
    out += ["", "## Catalogued patterns (distinct topics)", ""]
    out.append(", ".join(sorted(topics)) if topics else "_None yet._")
    out.append("")
    return "\n".join(out)


# --------------------------------------------------------------------------- #
# Per-platform
# --------------------------------------------------------------------------- #
def build_platform(platform: str, items: list[dict]) -> str:
    difficulty: Counter = Counter(c["difficulty"] for c in items)
    languages: Counter = Counter()
    topics: Counter = Counter()
    for c in items:
        for lang in c["langs"]:
            languages[lang] += 1
        for topic in c["topics"]:
            topics[topic] += 1

    out: list[str] = [
        f"# Index — {platform}",
        "",
        GEN_NOTE,
        "",
        f"**Total challenges solved:** {len(items)}",
        "",
        "## Solved per difficulty",
        "",
        *render_count_table("Difficulty", difficulty, key=lambda kv: diff_key(kv[0])),
        "",
        "## Solved per language",
        "",
        *render_count_table("Language", languages),
        "",
        "## Solved per type",
        "",
        *render_count_table("Type (topic)", topics),
        "",
        "## Challenges",
        "",
        "| ID | Title | Difficulty | Languages |",
        "| --- | --- | --- | --- |",
    ]
    for c in sorted(items, key=lambda x: id_key(x["id"])):
        langs = " · ".join(
            f"[{lang}](../{path})"
            for lang, path in sorted(c["langs"].items())
        )
        title = f"[{c['title']}]({c['url']})" if c["url"] else c["title"]
        cid = c["id"].zfill(4) if c["id"].isdigit() else c["id"]
        out.append(f"| {cid} | {title} | {c['difficulty']} | {langs} |")
    out.append("")
    return "\n".join(out)


# --------------------------------------------------------------------------- #
# README live-stats banner
# --------------------------------------------------------------------------- #
def readme_stats_lines(m: dict) -> list[str]:
    """Markdown injected between the README STATS markers. Deterministic (no
    timestamp), so an unchanged catalogue produces no diff."""
    return [
        "> Auto-generated by `scripts/gen_indexes.py` — do not edit between the "
        "STATS markers.",
        "",
        "| Metric | Value |",
        "| --- | ---: |",
        f"| Challenges solved | {m['total_challenges']} |",
        f"| Source platforms | {m['active_platforms']} active "
        f"(of {m['catalogued']} catalogued) |",
        f"| Languages used | {m['total_languages']} |",
        f"| Catalogued patterns | {m['total_patterns']} |",
    ]


def update_readme(m: dict) -> bool:
    """Rewrite the content between the README STATS markers in place. Returns
    True if the file changed. Non-fatal when the file or markers are absent so a
    repo without the banner still commits cleanly. Newlines are preserved as-is
    (read/write with ``newline=""``) to avoid rewriting the whole file's EOLs."""
    if not README.is_file():
        return False
    with README.open("r", encoding="utf-8", newline="") as fh:
        text = fh.read()
    marker = re.compile(
        re.escape(STATS_BEGIN) + ".*?" + re.escape(STATS_END), re.DOTALL
    )
    if not marker.search(text):
        print("gen_indexes: README STATS markers not found; skipped README banner.")
        return False
    nl = "\r\n" if "\r\n" in text else "\n"
    block = nl.join([STATS_BEGIN, *readme_stats_lines(m), STATS_END])
    new_text = marker.sub(lambda _: block, text, count=1)
    if new_text == text:
        return False
    with README.open("w", encoding="utf-8", newline="") as fh:
        fh.write(new_text)
    return True


# --------------------------------------------------------------------------- #
# Main
# --------------------------------------------------------------------------- #
def main() -> None:
    challenges = load_challenges()
    STATS.mkdir(parents=True, exist_ok=True)

    # Group challenges by platform.
    by_platform: dict[str, list[dict]] = {}
    for c in challenges.values():
        by_platform.setdefault(c["platform"], []).append(c)

    expected = {"index-overview.md"}
    (STATS / "index-overview.md").write_text(
        build_overview(challenges), encoding="utf-8"
    )
    for platform, items in by_platform.items():
        name = f"index-{platform}.md"
        expected.add(name)
        (STATS / name).write_text(build_platform(platform, items), encoding="utf-8")

    # Drop stale index files for platforms that no longer have solutions.
    for path in STATS.glob("index-*.md"):
        if path.name not in expected:
            path.unlink()

    readme_changed = update_readme(overview_metrics(challenges))

    print(
        f"Generated {len(expected)} index file(s) for "
        f"{len(challenges)} challenge(s) across {len(by_platform)} platform(s)"
        f"{'; refreshed README banner' if readme_changed else ''}."
    )


if __name__ == "__main__":
    main()
